import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { GoogleOAuthProvider } from '@react-oauth/google';
import toast, { Toaster } from "react-hot-toast";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const queryClient = new QueryClient()

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
    <QueryClientProvider client={queryClient}>

        <GoogleOAuthProvider clientId="71644079894-v5uuhpfl5rd5mja4plvqsdv4u0nqv2eh.apps.googleusercontent.com">
          {children}
          <Toaster/>
        </GoogleOAuthProvider>
    </QueryClientProvider>

      </body>
    </html>
  );
}
